### ISSUE TITLE
nacos 的mysql数据库init失败,为什么会去连接github站点，如果无法连接如何处理？

### ISSUE THREAD

**Issue by qingchen666** [ygqygq2/mysql-exec-sql#1]
root@k8s-master01-org:/opt/helm/nacos# kubectl logs nacos-cluster-pds-init-db-hlg5n  -n nacos
mysql: [Warning] Using a password on the command line interface can be insecure.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

**Comment by qingchen666** [comment]
同时在https://hub.docker.com/r/ygqygq2/mysql-exec-sql站点使用正确的Mysql连接信息初始化Mysql8的Nacos数据库,显示容器执行完成但数据库却并未生成相关表，如何处理？

docker run --rm -e MYSQL_HOST=10.200.200.70 -e MYSQL_PORT=3306 -e MYSQL_USER=root -e MYSQL_PASSWD='mypass' -e MYSQL_DB=nacos -e SQL_FILES="/tmp/1.sql /tmp/2.sql" -v /tmp/1.sql:/tmp/1.sql -v /tmp/2.sql:/tmp/2.sql k8s.harbor01.org/helm/docker.io/ygqygq2/mysql-exec-sql:latest /tmp/1.sql /tmp/2.sql

**Comment by ygqygq2** [comment]
这个主要是去 nacos 仓库下载 sql 文件然后导入。因为默认数据库并没有数据。
你用的哪个版本，我看下问题能不能优化，加个提示手动导入也不错。

**Comment by qingchen666** [comment]
您好，我是去到了Github仓库找到对应版本的SQL文件导入到外部Mysql后问题解决.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ygqygq2/mysql-exec-sql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月20日(星期一) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ygqygq2/mysql-exec-sql] nacos 的mysql数据库init失败,为什么会去连接github站点，如果无法连接如何处理？ (Issue #1)





 
这个主要是去 nacos 仓库下载 sql 文件然后导入。因为默认数据库并没有数据。
 你用的哪个版本，我看下问题能不能优化，加个提示手动导入也不错。

**Comment by ygqygq2** [comment]
是的，导进去就可以了。github 在大陆还是可以访问，只是有时会失败。
